### ISSUE TITLE
Some information about state?

### ISSUE THREAD

**Issue by GermanBluefox** [foxriver76/ioBroker.denon#18]
The only thing what I miss now to show such a widget:
![image](https://user-images.githubusercontent.com/4582016/43305186-133ba2c6-9177-11e8-811c-fe73fc9ee652.png)
is playerState.
Where can read about it?

**Comment by foxriver76** [comment]
With Player state you still mean the detection of isPaused?

**Comment by foxriver76** [comment]
in [AVR Protocol](/documentation/AVR-Control-Protocol.pdf) on page 8 at the bottom you will find the desired commands. The behaviour for the most commands is that you get some kind of acknowledge, but the media controls are declared as command only, which means that you won't get a response as far as I know (otherwise I would have implemented this). 

You can check by yourself, set the Adapter to Debug, press the button for pause, and look for an incoming message which confirms it. I tried it just now, but cant play music on it right now, because I'm only have access via VPN. But I'm like 99% sure that you wont get an acknowledge.

When you are using HEOS, there exists a completly different [protocol](http://rn.dmglobal.com/euheos/HEOS_CLI_ProtocolSpecification.pdf), which maybe enables this. But this shouldn't be a part of this adapter, because HEOS is not only AVR releated.

**Comment by GermanBluefox** [comment]
Yes it is about isPlaying/isPaused.
Thank you. Will check it. 
I don't know If I have a HEOS.. :)

**Comment by GermanBluefox** [comment]
I don'have heos. 
May be it is possible via  NSAx/Ex commands to read the display and guess...

**Comment by GermanBluefox** [comment]
Ok... I think I should give up and just accept it is not a player....
Thank you :)

пт, 27 июл. 2018 г. в 21:29, Max Hauser <notifications@github.com>:
