### ISSUE TITLE
zoneMain.skipPlus / skipMinus not working for AirPlay/Spotify/NET

### ISSUE THREAD

**Issue by arichter83** [foxriver76/ioBroker.denon#35]
Hey there! Great plugin, thank you very much for all your work. I have an Denon AVR-X6300H and wanted to add a prev/next for AirPlay & Spotify on NET. But nothing happens when I press the `denon.0.zoneMain.skipMinus`  button in the object list or call a script:

`setState('denon.0.zoneMain.skipMinus', true);
`

I noticed that it this is not available in the Denon AVR app either, but only in the HEOS app.

All the best from Berlin,
Andreas

**Comment by foxriver76** [comment]
Unfortunately it seems like this is only possible with the HEOS protocol, maybe this script helps you due to the fact that there isn’t a working adapter until now.
https://forum.iobroker.net/viewtopic.php?t=11241
So the buttons have absolutely no function on your HEOS AVR? If this is the case on all HEOS, I could remove them for HEOS devices in the adapter.

**Comment by arichter83** [comment]
@foxriver76 I did not check for CD/DVDs via Denon Link or for other USB/Storage devices. So maybe a comment in the docs is sufficient.

/* skipPlus / skipMinus will not work for HEOS AVR for AirPlay/Spotify */

**Comment by foxriver76** [comment]
Okay, thanks for the feedback I will add it to documentation.
