### ISSUE TITLE
Setting Display brightness not working (X1000)

### ISSUE THREAD

**Issue by aleks-83** [foxriver76/ioBroker.denon#64]
**Describe the bug**
When i set the display brightness into the datapoint "denon.0.display.brightness", the brightness at the display of my DENON X1000 doen't change.

**Versions:**
 - Adapter version: **1.7.1**
 - JS-Controller version: **2.1.0**
 - Node version: **v10.17.0**
 - NPM version: **6.11.3**
 - Operating system: **Win 10.0.18362** on a NUC
 - AVR model: **DENON X1000**

**Additional context**
Other commands like changing volume is working properly.

**Comment by foxriver76** [comment]
Hi, thanks for reporting. On X1200W it works, but it's not listed in the [protocol of X1000](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&ved=2ahUKEwiuqr_Bw4_mAhWEjKQKHcScCbsQFjACegQIBBAC&url=https%3A%2F%2Fwww.denon-hifi.ch%2Fchg%2Fproduct%2Fhometheater%2Favreceivers%2Favrx1000%3Fdocname%3DAVRX1000_E300_PROTOCOL(1000)_V01.pdf&usg=AOvVaw1srMmnC90I6Gy8OYxN8M-p)

So the reason is most likely, that X1000 doesn't support it.
