### ISSUE TITLE
Input/Source rename

### ISSUE THREAD

**Issue by Tschipel** [foxriver76/ioBroker.denon#83]
![Denon_Alias_01](https://user-images.githubusercontent.com/2829849/91209008-5da56b80-e70b-11ea-8baa-4344eaf9f86d.PNG)

Is it possible to import the alias from the renamed channels?

I'm using the Denon AVR-X4000.

**Comment by foxriver76** [comment]
Unfortunately there is no listed command in the telnet API description to perform this. If you find a possibility via telnet let me know

**Comment by SirTwistDo** [comment]
Hello Foxriver,
would it be possible to have a configuration field to fill with a (comma separated) list of input sources? E.g. my (very old) AVR-2805 has VCR-1 and VCR-2...
Kind regards,
Sir Twist

**Comment by foxriver76** [comment]
Currently, I don't know how I can get these information. The SI overview in the adapter is also only hard-coded. Unfortunately, I also cannot find a telnet protocol for this avr.

**Comment by SirTwistDo** [comment]
You are right, there is no telnet, nor a network connection at all. I connected the AVR via usb-to-serial-converter and used a tool "ser2telnet". I will raise another issue on that topic ;-) since I have some problems with that, but still am in investigation what is going wrong.
My suggestion would be to make the list I found in "main.js", line 1436ff, somehow configurable through the admin dialog. So anyone can adapt it to the own requirements. May that be possible?

**Comment by foxriver76** [comment]
No telnet but you are using it with this adapter?

**Comment by SirTwistDo** [comment]
Yes, Sorry, the software is called "ser2net" and maps just a tcp port to a serial port. Perhaps you want to include that option in your docs? If so, I can provide more details.
I used that for more than a year with openhab, now moved to iobroker and have some small issues with your Denon adapter. Sending commands is working absolutely fine, thanks a lot for your work with this adapter!
https://www.manualslib.com/download/38513/Denon-Avr-3805.html

**Comment by foxriver76** [comment]
Interesting approach. I will think about making the states list configurable. I will at least add the possible inputs of the AVR 3805.
